//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.WEB.Modules.Support.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.WEB.Modules.Support.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Last Error.
        /// </summary>
        public static string ImportLastError {
            get {
                return ResourceManager.GetString("ImportLastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string LinkFAQ {
            get {
                return ResourceManager.GetString("LinkFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policies.
        /// </summary>
        public static string LinkPrivacy {
            get {
                return ResourceManager.GetString("LinkPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string LinkTerm {
            get {
                return ResourceManager.GetString("LinkTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ticket.
        /// </summary>
        public static string NewTicketTitle {
            get {
                return ResourceManager.GetString("NewTicketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string OrderLast {
            get {
                return ResourceManager.GetString("OrderLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voted.
        /// </summary>
        public static string OrderVoted {
            get {
                return ResourceManager.GetString("OrderVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform versions available (click or scan).
        /// </summary>
        public static string PlatformVersionsAvailable {
            get {
                return ResourceManager.GetString("PlatformVersionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string TabAnnouncements {
            get {
                return ResourceManager.GetString("TabAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string TabDownloads {
            get {
                return ResourceManager.GetString("TabDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string TabFeedback {
            get {
                return ResourceManager.GetString("TabFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadmap.
        /// </summary>
        public static string TabRoadmap {
            get {
                return ResourceManager.GetString("TabRoadmap", resourceCulture);
            }
        }
    }
}
