//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.WEB.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Description {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Description() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.WEB.Translations.Description", typeof(Description).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your streaming platforms, manage your watch progress, and discover what to watch next with curated lists, award winners, and critic picks..
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore films and series that won the year’s top awards. Discover main categories, winners, and celebrated titles recognized by critics and audiences..
        /// </summary>
        internal static string AwardsYear {
            get {
                return ResourceManager.GetString("AwardsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Streaming Discovery with aggregators. Find where to watch, multi-source ratings, expert reviews, curated lists, and global availability..
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover our Editor’s Choice: films and series consistently rated highly across IMDb, TMDb, Metacritic, Rotten Tomatoes, Trakt, FilmAffinity, and Letterboxd..
        /// </summary>
        internal static string EditorsChoice {
            get {
                return ResourceManager.GetString("EditorsChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the most anticipated movies of {0}, featuring upcoming blockbusters, fan favorites, and highly awaited releases hitting theaters and streaming..
        /// </summary>
        internal static string ExpectedMovies {
            get {
                return ResourceManager.GetString("ExpectedMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover free movies and series you can watch legally. Updated daily with streaming availability across multiple platforms..
        /// </summary>
        internal static string FreeWatch {
            get {
                return ResourceManager.GetString("FreeWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover free {0} you can watch legally in {1}. Updated daily with streaming availability across multiple platforms..
        /// </summary>
        internal static string FreeWatchExtended {
            get {
                return ResourceManager.GetString("FreeWatchExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get detailed guides, troubleshooting tips, FAQs, and contact support for {0}. Solve issues and discover features easily..
        /// </summary>
        internal static string HelpCenter {
            get {
                return ResourceManager.GetString("HelpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how Modern Matchmaker evaluates compatibility, suggests meaningful matches, and offers a smarter alternative to traditional dating and matchmaking..
        /// </summary>
        internal static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the latest movies, TV shows, celebrity news, and pop culture updates. Stay informed on all things entertainment..
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the latest movies, TV shows, celebrity news, and pop culture updates..
        /// </summary>
        internal static string NewsShort {
            get {
                return ResourceManager.GetString("NewsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse streaming services offering movies, TV shows, and documentaries. Discover platforms for every taste, from mainstream hits to niche content..
        /// </summary>
        internal static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See last week’s most popular movies, TV shows, and stars, ranked by audience interest. Stay up-to-date on trending entertainment picks..
        /// </summary>
        internal static string PopularIndex {
            get {
                return ResourceManager.GetString("PopularIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch the latest movie trailers and teasers in HD. Stay updated on upcoming films, blockbusters, and must-see releases..
        /// </summary>
        internal static string Trailers {
            get {
                return ResourceManager.GetString("Trailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch the latest movie trailers and teasers in HD..
        /// </summary>
        internal static string TrailersShort {
            get {
                return ResourceManager.GetString("TrailersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Matchmaker is for people seeking meaningful, long-term relationships without the limits of dating apps or the high cost of traditional matchmaking..
        /// </summary>
        internal static string WhoIsItFor {
            get {
                return ResourceManager.GetString("WhoIsItFor", resourceCulture);
            }
        }
    }
}
