//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.WEB.Translations.Module {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Landing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Landing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.WEB.Translations.Module.Landing", typeof(Landing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility System.
        /// </summary>
        internal static string Approach01 {
            get {
                return ResourceManager.GetString("Approach01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We suggest matches using our compatibility system that evaluates values, lifestyle, and relationship goals..
        /// </summary>
        internal static string Approach01Desc {
            get {
                return ResourceManager.GetString("Approach01Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intentional Connections.
        /// </summary>
        internal static string Approach02 {
            get {
                return ResourceManager.GetString("Approach02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our platform is designed to support serious relationships by focusing on meaningful introductions rather than casual browsing..
        /// </summary>
        internal static string Approach02Desc {
            get {
                return ResourceManager.GetString("Approach02Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Profiles.
        /// </summary>
        internal static string Approach03 {
            get {
                return ResourceManager.GetString("Approach03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity and photo verification are required before interaction to help ensure authenticity and trust..
        /// </summary>
        internal static string Approach03Desc {
            get {
                return ResourceManager.GetString("Approach03Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and Security.
        /// </summary>
        internal static string Approach04 {
            get {
                return ResourceManager.GetString("Approach04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our platform protects your data and provides a secure environment for all users, giving you confidence while connecting..
        /// </summary>
        internal static string Approach04Desc {
            get {
                return ResourceManager.GetString("Approach04Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks Currency.
        /// </summary>
        internal static string Approach05 {
            get {
                return ResourceManager.GetString("Approach05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks are our virtual currency used to access premium actions and features across the platform..
        /// </summary>
        internal static string Approach05Desc {
            get {
                return ResourceManager.GetString("Approach05Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Features Ahead.
        /// </summary>
        internal static string Approach06 {
            get {
                return ResourceManager.GetString("Approach06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the platform grows, new matchmaking features and enhancements will be unlocked for more ways to connect..
        /// </summary>
        internal static string Approach06Desc {
            get {
                return ResourceManager.GetString("Approach06Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare us with typical dating apps and see what makes our approach different. Explore the key features that set us apart and create more meaningful connections..
        /// </summary>
        internal static string CompareCall {
            get {
                return ResourceManager.GetString("CompareCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the difference for yourself and discover matches based on real compatibility..
        /// </summary>
        internal static string CompareCall2 {
            get {
                return ResourceManager.GetString("CompareCall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility System.
        /// </summary>
        internal static string CompatibilitySystem {
            get {
                return ResourceManager.GetString("CompatibilitySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have developed the most advanced and scientifically backed compatibility system to create meaningful, long-lasting relationships..
        /// </summary>
        internal static string CompatibilitySystemDesc {
            get {
                return ResourceManager.GetString("CompatibilitySystemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries where users have registered so far.
        /// </summary>
        internal static string CountriesRegistered {
            get {
                return ResourceManager.GetString("CountriesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a keyword or theme.
        /// </summary>
        internal static string EnterKeyword {
            get {
                return ResourceManager.GetString("EnterKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a title or name.
        /// </summary>
        internal static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how we match you with people who fit your lifestyle, values, and goals. Learn about the step-by-step process and how Sparks help you engage meaningfully..
        /// </summary>
        internal static string HowItWorksCall {
            get {
                return ResourceManager.GetString("HowItWorksCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now that you know how it works, take the first step towards finding your soulmate..
        /// </summary>
        internal static string HowItWorksCall2 {
            get {
                return ResourceManager.GetString("HowItWorksCall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Users.
        /// </summary>
        internal static string LastUsers {
            get {
                return ResourceManager.GetString("LastUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users who recently registered on the platform.
        /// </summary>
        internal static string LastUsersSubtitle {
            get {
                return ResourceManager.GetString("LastUsersSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Approach.
        /// </summary>
        internal static string OurApproach {
            get {
                return ResourceManager.GetString("OurApproach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Numbers.
        /// </summary>
        internal static string OurNumbers {
            get {
                return ResourceManager.GetString("OurNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together we are building something amazing!.
        /// </summary>
        internal static string OurNumbersMsg1 {
            get {
                return ResourceManager.GetString("OurNumbersMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our numbers are growing every day. Join our community and find your perfect match..
        /// </summary>
        internal static string OurNumbersMsg2 {
            get {
                return ResourceManager.GetString("OurNumbersMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Roadmap.
        /// </summary>
        internal static string OurRoadmap {
            get {
                return ResourceManager.GetString("OurRoadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Features Unlocked as Our Community Expands!.
        /// </summary>
        internal static string OurRoadmapMsg1 {
            get {
                return ResourceManager.GetString("OurRoadmapMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are constantly evolving! Features may be released early if development is completed ahead of schedule. We appreciate your feedback, and your suggestions can help shape the future of our platform!.
        /// </summary>
        internal static string OurRoadmapMsg2 {
            get {
                return ResourceManager.GetString("OurRoadmapMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our matchmaking pool.
        /// </summary>
        internal static string Phase1Opt1 {
            get {
                return ResourceManager.GetString("Phase1Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore our compatibility system.
        /// </summary>
        internal static string Phase1Opt2 {
            get {
                return ResourceManager.GetString("Phase1Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks: US$1 per unit.
        /// </summary>
        internal static string Phase1Opt3 {
            get {
                return ResourceManager.GetString("Phase1Opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 1 (0-10k users).
        /// </summary>
        internal static string Phase1Title {
            get {
                return ResourceManager.GetString("Phase1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users can apply as matchmaking clients.
        /// </summary>
        internal static string Phase2Opt1 {
            get {
                return ResourceManager.GetString("Phase2Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks: US$2 per unit.
        /// </summary>
        internal static string Phase2Opt3 {
            get {
                return ResourceManager.GetString("Phase2Opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 2 (10k-20k users).
        /// </summary>
        internal static string Phase2Title {
            get {
                return ResourceManager.GetString("Phase2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotlight - Boost your profile on the platform..
        /// </summary>
        internal static string Phase3Opt1 {
            get {
                return ResourceManager.GetString("Phase3Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks: US$3 per unit.
        /// </summary>
        internal static string Phase3Opt2 {
            get {
                return ResourceManager.GetString("Phase3Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 3 (20k-30k users).
        /// </summary>
        internal static string Phase3Title {
            get {
                return ResourceManager.GetString("Phase3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New features to be announced.
        /// </summary>
        internal static string Phase4Opt1 {
            get {
                return ResourceManager.GetString("Phase4Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks: US$4 per unit.
        /// </summary>
        internal static string Phase4Opt2 {
            get {
                return ResourceManager.GetString("Phase4Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 4 (30k-40k users).
        /// </summary>
        internal static string Phase4Title {
            get {
                return ResourceManager.GetString("Phase4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Joined.
        /// </summary>
        internal static string RecentlyJoined {
            get {
                return ResourceManager.GetString("RecentlyJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for keywords related to movies and TV series (English only)..
        /// </summary>
        internal static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search terms returned no results. Please change them and try again..
        /// </summary>
        internal static string SearchReturnedNothing {
            get {
                return ResourceManager.GetString("SearchReturnedNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        internal static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for movies, series or people.
        /// </summary>
        internal static string TypeSomething {
            get {
                return ResourceManager.GetString("TypeSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover if Modern Matchmaker is right for you and your relationship goals. Understand who benefits most from our intentional approach to serious dating..
        /// </summary>
        internal static string WhoIsItForCall {
            get {
                return ResourceManager.GetString("WhoIsItForCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now that you know this platform was made for you, take the first step towards finding your soulmate..
        /// </summary>
        internal static string WhoIsItForCall2 {
            get {
                return ResourceManager.GetString("WhoIsItForCall2", resourceCulture);
            }
        }
    }
}
