//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.WEB.Translations.Module {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.WEB.Translations.Module.Profile", typeof(Profile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add titles to your wishlist to appear here.
        /// </summary>
        internal static string AddTitlesWishlist {
            get {
                return ResourceManager.GetString("AddTitlesWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Providers.
        /// </summary>
        internal static string AuthProviders {
            get {
                return ResourceManager.GetString("AuthProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The basic section is mandatory for now. The other sections can be filled in later..
        /// </summary>
        internal static string BasicRequired {
            get {
                return ResourceManager.GetString("BasicRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only your age will be published. (We use the Gregorian calendar).
        /// </summary>
        internal static string BirthdateTip {
            get {
                return ResourceManager.GetString("BirthdateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Photo.
        /// </summary>
        internal static string BodyPhoto {
            get {
                return ResourceManager.GetString("BodyPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        internal static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our compatibility system is still developing. If you have any suggestions or feedback, please submit a support ticket or email us..
        /// </summary>
        internal static string CompatibilityDeveloping {
            get {
                return ResourceManager.GetString("CompatibilityDeveloping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you two are made for each other. This relationship has a bright future ahead of it..
        /// </summary>
        internal static string CompatibilityHigh {
            get {
                return ResourceManager.GetString("CompatibilityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you don&apos;t have much in common. We wish you both the best of luck, as it won&apos;t be an easy task..
        /// </summary>
        internal static string CompatibilityLow {
            get {
                return ResourceManager.GetString("CompatibilityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a perfect couple, but that doesn&apos;t mean that the relationship will fail. Review our report carefully and work through these differences together..
        /// </summary>
        internal static string CompatibilityMedium {
            get {
                return ResourceManager.GetString("CompatibilityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make your profile public, first complete all the steps.
        /// </summary>
        internal static string CompleteAllSteps {
            get {
                return ResourceManager.GetString("CompleteAllSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete your profile.
        /// </summary>
        internal static string CompleteYourProfile {
            get {
                return ResourceManager.GetString("CompleteYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve set up your profile with a few sample items to give you a quick tour of the available features..
        /// </summary>
        internal static string DemoAlert {
            get {
                return ResourceManager.GetString("DemoAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Compatibility.
        /// </summary>
        internal static string ExpectedCompatibility {
            get {
                return ResourceManager.GetString("ExpectedCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Photo.
        /// </summary>
        internal static string FacePhoto {
            get {
                return ResourceManager.GetString("FacePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is only available in phase {0}.
        /// </summary>
        internal static string FeatureNotAvailable {
            get {
                return ResourceManager.GetString("FeatureNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow titles so they appear here (if it is a series or a movie that is part of a sequence)..
        /// </summary>
        internal static string FollowTitle {
            get {
                return ResourceManager.GetString("FollowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo taken by your camera will be kept private (it will not be accessible within the platform) for future verification, if necessary..
        /// </summary>
        internal static string GalleryTerm1 {
            get {
                return ResourceManager.GetString("GalleryTerm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data resulting from this validation (attributes of your face) will not be kept on our servers and will only exist during the detection process..
        /// </summary>
        internal static string GalleryTerm2 {
            get {
                return ResourceManager.GetString("GalleryTerm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Validation.
        /// </summary>
        internal static string GalleryValidation {
            get {
                return ResourceManager.GetString("GalleryValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Compatibility.
        /// </summary>
        internal static string GeneralCompatibility {
            get {
                return ResourceManager.GetString("GeneralCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate a match simulation? This is just to demonstrate how our compatibility system works..
        /// </summary>
        internal static string GenerateSimulation {
            get {
                return ResourceManager.GetString("GenerateSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPS position is not accurate and may result in an incorrect location. If your city is wrong, please try again later or test on another device or browser..
        /// </summary>
        internal static string GpsNotAccurate {
            get {
                return ResourceManager.GetString("GpsNotAccurate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us unlock the next phase faster! Leave a review to help us grow. The more people who know about the app and sign up, the sooner all the features will be available for you to enjoy..
        /// </summary>
        internal static string HelpUsUnlock {
            get {
                return ResourceManager.GetString("HelpUsUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Free Account.
        /// </summary>
        internal static string HeroButton {
            get {
                return ResourceManager.GetString("HeroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your journey to find your ideal partner.
        /// </summary>
        internal static string HeroCall {
            get {
                return ResourceManager.GetString("HeroCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Not a dating app. A curated matchmaking experience focused on real compatibility..
        /// </summary>
        internal static string HeroNote {
            get {
                return ResourceManager.GetString("HeroNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        internal static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I trust the platform&apos;s compatibility system and will only select what is non-negotiable for me..
        /// </summary>
        internal static string ITrustPlataform {
            get {
                return ResourceManager.GetString("ITrustPlataform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        internal static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark platforms as favorites to appear here.
        /// </summary>
        internal static string MarkPlatforms {
            get {
                return ResourceManager.GetString("MarkPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a maximum of 3 items for each field.
        /// </summary>
        internal static string Maximum3Items {
            get {
                return ResourceManager.GetString("Maximum3Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following - Movies.
        /// </summary>
        internal static string MyMovieFollowing {
            get {
                return ResourceManager.GetString("MyMovieFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist - Movies.
        /// </summary>
        internal static string MyMovieWishlist {
            get {
                return ResourceManager.GetString("MyMovieWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Platforms.
        /// </summary>
        internal static string MyPlatforms {
            get {
                return ResourceManager.GetString("MyPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following - Series.
        /// </summary>
        internal static string MySeriesFollowing {
            get {
                return ResourceManager.GetString("MySeriesFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist - Series.
        /// </summary>
        internal static string MySeriesWishlist {
            get {
                return ResourceManager.GetString("MySeriesWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not answered.
        /// </summary>
        internal static string NotAnswered {
            get {
                return ResourceManager.GetString("NotAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (optional section).
        /// </summary>
        internal static string OptionalSection {
            get {
                return ResourceManager.GetString("OptionalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner&apos;s profile is not yet available.
        /// </summary>
        internal static string PartnerProfileNotAvailable {
            get {
                return ResourceManager.GetString("PartnerProfileNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        internal static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process is constantly evolving. If you would like to report an error or improvement, please open a ticket with our support team..
        /// </summary>
        internal static string PopulateFilterDescription {
            get {
                return ResourceManager.GetString("PopulateFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields automatically populated.
        /// </summary>
        internal static string PopulateFilterTitle {
            get {
                return ResourceManager.GetString("PopulateFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can define your ideal profile type, so that we can properly calculate your compatibility index.
        /// </summary>
        internal static string PreferHelpTopic1 {
            get {
                return ResourceManager.GetString("PreferHelpTopic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The more specific you are in the filters, the less profile options you will have available.
        /// </summary>
        internal static string PreferHelpTopic2 {
            get {
                return ResourceManager.GetString("PreferHelpTopic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure a positive environment, we take harassment and bias seriously. If you encounter this type of behavior, please report the profile immediately..
        /// </summary>
        internal static string ProfileDataBioTip1 {
            get {
                return ResourceManager.GetString("ProfileDataBioTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find it challenging to interact or recognize harmful intentions, consider reaching out to friends or family for support..
        /// </summary>
        internal static string ProfileDataBioTip2 {
            get {
                return ResourceManager.GetString("ProfileDataBioTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more complex personalities, explore tests on specialized sites. Some can be answered just by reading the item descriptions..
        /// </summary>
        internal static string ProfileDataPersonTip1 {
            get {
                return ResourceManager.GetString("ProfileDataPersonTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only what really matters. You can choose up to 8 filters to keep matches relevant..
        /// </summary>
        internal static string ProfileFilterWarning {
            get {
                return ResourceManager.GetString("ProfileFilterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not available.
        /// </summary>
        internal static string ProfileNotAvailable {
            get {
                return ResourceManager.GetString("ProfileNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not found or not yet registered properly..
        /// </summary>
        internal static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is now in private mode and will not be seen or shared with anyone.
        /// </summary>
        internal static string ProfilePrivateMode {
            get {
                return ResourceManager.GetString("ProfilePrivateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is now public and can be made available to our customers.
        /// </summary>
        internal static string ProfilePublicMode {
            get {
                return ResourceManager.GetString("ProfilePublicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions have been automatically applied for your favorite providers. If they are wrong, please remove and add them again..
        /// </summary>
        internal static string RegionsApplied {
            get {
                return ResourceManager.GetString("RegionsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Filters.
        /// </summary>
        internal static string StepFilter {
            get {
                return ResourceManager.GetString("StepFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your non-negotiable preferences..
        /// </summary>
        internal static string StepFilterDesc {
            get {
                return ResourceManager.GetString("StepFilterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        internal static string StepGallery {
            get {
                return ResourceManager.GetString("StepGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload and organize your photos..
        /// </summary>
        internal static string StepGalleryDesc {
            get {
                return ResourceManager.GetString("StepGalleryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Profile.
        /// </summary>
        internal static string StepProfile {
            get {
                return ResourceManager.GetString("StepProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in your details: Basic, Bio, Lifestyle, Personality, Interests, Relationship, and Goals..
        /// </summary>
        internal static string StepProfileDesc {
            get {
                return ResourceManager.GetString("StepProfileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Settings.
        /// </summary>
        internal static string StepSettings {
            get {
                return ResourceManager.GetString("StepSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control your profile options and platform behavior..
        /// </summary>
        internal static string StepSettingsDesc {
            get {
                return ResourceManager.GetString("StepSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Validation.
        /// </summary>
        internal static string StepValidation {
            get {
                return ResourceManager.GetString("StepValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system will verify your information before your profile goes public..
        /// </summary>
        internal static string StepValidationDesc {
            get {
                return ResourceManager.GetString("StepValidationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        internal static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be honest in the answers given on this form. All information contained herein is open to denouncements and may be evaluated;.
        /// </summary>
        internal static string TermTopic1 {
            get {
                return ResourceManager.GetString("TermTopic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be aware of how your data will be treated, we ask you to read our.
        /// </summary>
        internal static string TermTopic2 {
            get {
                return ResourceManager.GetString("TermTopic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to detect a GPS system on your device. Please try again or release access to your device&apos;s GPS..
        /// </summary>
        internal static string UnableDetectGps {
            get {
                return ResourceManager.GetString("UnableDetectGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What items have you already watched?.
        /// </summary>
        internal static string WhatHaveYouWatched {
            get {
                return ResourceManager.GetString("WhatHaveYouWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why is it important?.
        /// </summary>
        internal static string WhyImportant {
            get {
                return ResourceManager.GetString("WhyImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        internal static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected more than {0} options.
        /// </summary>
        internal static string YouHaveSelected {
            get {
                return ResourceManager.GetString("YouHaveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current location:.
        /// </summary>
        internal static string YourCurrentLocation {
            get {
                return ResourceManager.GetString("YourCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner&apos;s profile.
        /// </summary>
        internal static string YourPartnerProfile {
            get {
                return ResourceManager.GetString("YourPartnerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile (or preferences).
        /// </summary>
        internal static string YourProfile {
            get {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }
    }
}
