//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.WEB.Modules.Collections.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.WEB.Modules.Collections.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to wishlist.
        /// </summary>
        public static string AddWishlist {
            get {
                return ResourceManager.GetString("AddWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major film and TV awards honoring excellence in acting, directing, animation, and overall production across global entertainment industries..
        /// </summary>
        public static string AwardsDescription {
            get {
                return ResourceManager.GetString("AwardsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards.
        /// </summary>
        public static string AwardsTitle {
            get {
                return ResourceManager.GetString("AwardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as unwatched.
        /// </summary>
        public static string ButtonNotWatched {
            get {
                return ResourceManager.GetString("ButtonNotWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as watched.
        /// </summary>
        public static string ButtonWatched {
            get {
                return ResourceManager.GetString("ButtonWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        public static string Cast {
            get {
                return ResourceManager.GetString("Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified by SD.
        /// </summary>
        public static string CertifiedSDTitle {
            get {
                return ResourceManager.GetString("CertifiedSDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string DeliveryModelAds {
            get {
                return ResourceManager.GetString("DeliveryModelAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string DeliveryModelBuy {
            get {
                return ResourceManager.GetString("DeliveryModelBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Rate.
        /// </summary>
        public static string DeliveryModelFlatRate {
            get {
                return ResourceManager.GetString("DeliveryModelFlatRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Rate/Buy.
        /// </summary>
        public static string DeliveryModelFlatRateBuy {
            get {
                return ResourceManager.GetString("DeliveryModelFlatRateBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string DeliveryModelFree {
            get {
                return ResourceManager.GetString("DeliveryModelFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string DeliveryModelRent {
            get {
                return ResourceManager.GetString("DeliveryModelRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directing.
        /// </summary>
        public static string Directing {
            get {
                return ResourceManager.GetString("Directing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information or Contributions.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overview not available in your language.
        /// </summary>
        public static string NoPlot {
            get {
                return ResourceManager.GetString("NoPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offering.
        /// </summary>
        public static string Offering {
            get {
                return ResourceManager.GetString("Offering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform added successfully!.
        /// </summary>
        public static string PlatformAdded {
            get {
                return ResourceManager.GetString("PlatformAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform is not for watching movies or series..
        /// </summary>
        public static string PlatformForManaging {
            get {
                return ResourceManager.GetString("PlatformForManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform removed successfully!.
        /// </summary>
        public static string PlatformRemoved {
            get {
                return ResourceManager.GetString("PlatformRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related links.
        /// </summary>
        public static string RelatedLinks {
            get {
                return ResourceManager.GetString("RelatedLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from wishlist.
        /// </summary>
        public static string RemoveWishlist {
            get {
                return ResourceManager.GetString("RemoveWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted platforms providing reviews, ratings, industry news, and entertainment data for movies, shows, and streaming content..
        /// </summary>
        public static string SpecializedSitesDescription {
            get {
                return ResourceManager.GetString("SpecializedSitesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialized Sites.
        /// </summary>
        public static string SpecializedSitesTitle {
            get {
                return ResourceManager.GetString("SpecializedSitesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated collections focused on franchises, studios, platforms, and popular themes to help you discover standout content..
        /// </summary>
        public static string SpecialsDescription {
            get {
                return ResourceManager.GetString("SpecialsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        public static string SpecialsTitle {
            get {
                return ResourceManager.GetString("SpecialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TabAbout {
            get {
                return ResourceManager.GetString("TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequels.
        /// </summary>
        public static string TabCollection1 {
            get {
                return ResourceManager.GetString("TabCollection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string TabCollection2 {
            get {
                return ResourceManager.GetString("TabCollection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string TabCredits {
            get {
                return ResourceManager.GetString("TabCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to Watch.
        /// </summary>
        public static string TabWhereToWatch {
            get {
                return ResourceManager.GetString("TabWhereToWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title is not available in your region: {0}.
        /// </summary>
        public static string TitleNotAvailable {
            get {
                return ResourceManager.GetString("TitleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie/Series not yet released.
        /// </summary>
        public static string TitleNotReleased {
            get {
                return ResourceManager.GetString("TitleNotReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
    }
}
