//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.WEB.Modules.Profile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.WEB.Modules.Profile.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Information.
        /// </summary>
        public static string AccessInformation {
            get {
                return ResourceManager.GetString("AccessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile in Gravatar.
        /// </summary>
        public static string EditProfileGravatar {
            get {
                return ResourceManager.GetString("EditProfileGravatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Provider.
        /// </summary>
        public static string IdentityProvider {
            get {
                return ResourceManager.GetString("IdentityProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching - Movies.
        /// </summary>
        public static string MyMovieWatching {
            get {
                return ResourceManager.GetString("MyMovieWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist - Movies.
        /// </summary>
        public static string MyMovieWishlist {
            get {
                return ResourceManager.GetString("MyMovieWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile (Gravatar).
        /// </summary>
        public static string MyProfileGravatar {
            get {
                return ResourceManager.GetString("MyProfileGravatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Providers.
        /// </summary>
        public static string MyProviders {
            get {
                return ResourceManager.GetString("MyProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching - Shows.
        /// </summary>
        public static string MyShowWatching {
            get {
                return ResourceManager.GetString("MyShowWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist - Shows.
        /// </summary>
        public static string MyShowWishlist {
            get {
                return ResourceManager.GetString("MyShowWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Suggestions.
        /// </summary>
        public static string MySuggestions {
            get {
                return ResourceManager.GetString("MySuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our suggestions are based on the providers you&apos;ve favorited.
        /// </summary>
        public static string OurSuggestions1 {
            get {
                return ResourceManager.GetString("OurSuggestions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our suggestions are based on your favorite providers and your genre preferences (excluding titles that are already on your personal lists)..
        /// </summary>
        public static string OurSuggestions2 {
            get {
                return ResourceManager.GetString("OurSuggestions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo (Last).
        /// </summary>
        public static string PhotoLast {
            get {
                return ResourceManager.GetString("PhotoLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions have been automatically applied for your favorite providers. If they are wrong, please remove and add them again..
        /// </summary>
        public static string RegionsApplied {
            get {
                return ResourceManager.GetString("RegionsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferences will take effect in the next update of this list.
        /// </summary>
        public static string UpdateMySuggestions {
            get {
                return ResourceManager.GetString("UpdateMySuggestions", resourceCulture);
            }
        }
    }
}
