//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Credit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Credit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.WEB.Resources.Credit", typeof(Credit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JustWatch is a streaming guide that helps users find where movies and TV shows are available online..
        /// </summary>
        public static string JustWatch {
            get {
                return ResourceManager.GetString("JustWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of the most anticipated movies of 2025, based on buzz, announcements, and audience interest..
        /// </summary>
        public static string MostExpectedMovies2025 {
            get {
                return ResourceManager.GetString("MostExpectedMovies2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of the most anticipated movies of 2026, based on early announcements, hype, and fan expectations..
        /// </summary>
        public static string MostExpectedMovies2026 {
            get {
                return ResourceManager.GetString("MostExpectedMovies2026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MudBlazor is an open-source UI component library for building modern web applications with Blazor and Material Design..
        /// </summary>
        public static string MudBlazor {
            get {
                return ResourceManager.GetString("MudBlazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB (The Movie Database) is a community-built database for movies, TV shows, and related metadata and images..
        /// </summary>
        public static string TMDB {
            get {
                return ResourceManager.GetString("TMDB", resourceCulture);
            }
        }
    }
}
