//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.WEB.Resources.GlobalTranslations", typeof(GlobalTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Language.
        /// </summary>
        public static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translates the app interface. Partial translations may apply for some languages..
        /// </summary>
        public static string AppLanguageDesc {
            get {
                return ResourceManager.GetString("AppLanguageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films and series that won the main awards of the year.
        /// </summary>
        public static string AwardsYearDescription {
            get {
                return ResourceManager.GetString("AwardsYearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive selection from Streaming Discovery (Only films and series with 4 or more green ratings are included in this list).
        /// </summary>
        public static string CertifiedDescription {
            get {
                return ResourceManager.GetString("CertifiedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore our other amazing apps:.
        /// </summary>
        public static string CheckOurApps {
            get {
                return ResourceManager.GetString("CheckOurApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Language.
        /// </summary>
        public static string ContentLanguage {
            get {
                return ResourceManager.GetString("ContentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translates titles, descriptions, posters, and other content from movies or TV shows..
        /// </summary>
        public static string ContentLanguageDesc {
            get {
                return ResourceManager.GetString("ContentLanguageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation. Please try again..
        /// </summary>
        public static string CustomVisibilityInvalid {
            get {
                return ResourceManager.GetString("CustomVisibilityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CustomVisibilityLoading {
            get {
                return ResourceManager.GetString("CustomVisibilityLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not available.
        /// </summary>
        public static string CustomVisibilityNoData {
            get {
                return ResourceManager.GetString("CustomVisibilityNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover our other products.
        /// </summary>
        public static string DiscoverProducts {
            get {
                return ResourceManager.GetString("DiscoverProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already used all your available energy. It&apos;s automatically recharged once a week. Upgrade to Premium to get extra energy and keep exploring..
        /// </summary>
        public static string EnergyOut {
            get {
                return ResourceManager.GetString("EnergyOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing a movie or series consumes energy. Subscribers have a higher energy limit to explore more..
        /// </summary>
        public static string EnergyTooltip {
            get {
                return ResourceManager.GetString("EnergyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for news....
        /// </summary>
        public static string FeatureUnavailableDescription {
            get {
                return ResourceManager.GetString("FeatureUnavailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under development.
        /// </summary>
        public static string FeatureUnavailableMessage {
            get {
                return ResourceManager.GetString("FeatureUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        public static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled!.
        /// </summary>
        public static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully!.
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week&apos;s most popular movies, TV shows, and movie stars based on audience interest..
        /// </summary>
        public static string PopularIndexDescription {
            get {
                return ResourceManager.GetString("PopularIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Feature.
        /// </summary>
        public static string PremiumFeature {
            get {
                return ResourceManager.GetString("PremiumFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE NOW.
        /// </summary>
        public static string PWAUpdaterButton {
            get {
                return ResourceManager.GetString("PWAUpdaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available.
        /// </summary>
        public static string PWAUpdaterText {
            get {
                return ResourceManager.GetString("PWAUpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter platforms and content by region..
        /// </summary>
        public static string RegionDesc {
            get {
                return ResourceManager.GetString("RegionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Collection.
        /// </summary>
        public static string RemoveCollection {
            get {
                return ResourceManager.GetString("RemoveCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search terms returned no results. Please change them and try again..
        /// </summary>
        public static string SearchReturnedNothing {
            get {
                return ResourceManager.GetString("SearchReturnedNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all items.
        /// </summary>
        public static string SeeAllItems {
            get {
                return ResourceManager.GetString("SeeAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion Filters.
        /// </summary>
        public static string SuggestionFilters {
            get {
                return ResourceManager.GetString("SuggestionFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account? This action cannot be undone..
        /// </summary>
        public static string SureDeleteAccount {
            get {
                return ResourceManager.GetString("SureDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for movies, series or people.
        /// </summary>
        public static string TypeSomething {
            get {
                return ResourceManager.GetString("TypeSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What items have you already watched?.
        /// </summary>
        public static string WhatHaveYouWatched {
            get {
                return ResourceManager.GetString("WhatHaveYouWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the app and share it with your friends!.
        /// </summary>
        public static string WriteReviewSubtitle {
            get {
                return ResourceManager.GetString("WriteReviewSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the store link doesn&apos;t work, try going directly to the website..
        /// </summary>
        public static string WriteReviewSubtitleStore {
            get {
                return ResourceManager.GetString("WriteReviewSubtitleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help {0} grow!.
        /// </summary>
        public static string WriteReviewTitle {
            get {
                return ResourceManager.GetString("WriteReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in.
        /// </summary>
        public static string YouMustLogged {
            get {
                return ResourceManager.GetString("YouMustLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to subscribe.
        /// </summary>
        public static string YouMustLoggedSubscribe {
            get {
                return ResourceManager.GetString("YouMustLoggedSubscribe", resourceCulture);
            }
        }
    }
}
