//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeliveryModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeliveryModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.Shared.Resources.Enum.DeliveryModel", typeof(DeliveryModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad-based video on demand (AVOD) doesn’t require a subscription or transactional fee, as it’s ad-supported content..
        /// </summary>
        public static string AVODDescription {
            get {
                return ResourceManager.GetString("AVODDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        public static string AVODName {
            get {
                return ResourceManager.GetString("AVODName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string FREEDescription {
            get {
                return ResourceManager.GetString("FREEDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string FREEName {
            get {
                return ResourceManager.GetString("FREEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium video on demand (PVOD) is a newer concept, where film studios and other providers offer premium video content, like access to a movie premiere, at a higher price point..
        /// </summary>
        public static string PVODDescription {
            get {
                return ResourceManager.GetString("PVODDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string PVODName {
            get {
                return ResourceManager.GetString("PVODName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription video on demand (SVOD) is content accessible to consumers who have signed up for a subscription to a particular service, allowing them to view as much as they want for a flat rate per month..
        /// </summary>
        public static string SVODDescription {
            get {
                return ResourceManager.GetString("SVODDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string SVODName {
            get {
                return ResourceManager.GetString("SVODName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactional video on demand (TVOD) content is purchased through a pay-per-view model. Viewers can either purchase the content for repeated viewing, or rent it for a single-time use..
        /// </summary>
        public static string TVODDescription {
            get {
                return ResourceManager.GetString("TVODDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string TVODName {
            get {
                return ResourceManager.GetString("TVODName", resourceCulture);
            }
        }
    }
}
