//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.Shared.Resources.Enum.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (AE).
        /// </summary>
        public static string ar_AE {
            get {
                return ResourceManager.GetString("ar-AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (SA).
        /// </summary>
        public static string ar_SA {
            get {
                return ResourceManager.GetString("ar-SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian (BY).
        /// </summary>
        public static string be_BY {
            get {
                return ResourceManager.GetString("be-BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian (BG).
        /// </summary>
        public static string bg_BG {
            get {
                return ResourceManager.GetString("bg-BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string bn_BD {
            get {
                return ResourceManager.GetString("bn-BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan (ES).
        /// </summary>
        public static string ca_ES {
            get {
                return ResourceManager.GetString("ca-ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ch_GU {
            get {
                return ResourceManager.GetString("ch-GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string cn_CN {
            get {
                return ResourceManager.GetString("cn-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech (CZ).
        /// </summary>
        public static string cs_CZ {
            get {
                return ResourceManager.GetString("cs-CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish (DK).
        /// </summary>
        public static string da_DK {
            get {
                return ResourceManager.GetString("da-DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (AT).
        /// </summary>
        public static string de_AT {
            get {
                return ResourceManager.GetString("de-AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (CH).
        /// </summary>
        public static string de_CH {
            get {
                return ResourceManager.GetString("de-CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (DE).
        /// </summary>
        public static string de_DE {
            get {
                return ResourceManager.GetString("de-DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (GR).
        /// </summary>
        public static string el_GR {
            get {
                return ResourceManager.GetString("el-GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (AU).
        /// </summary>
        public static string en_AU {
            get {
                return ResourceManager.GetString("en-AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (CA).
        /// </summary>
        public static string en_CA {
            get {
                return ResourceManager.GetString("en-CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (GB).
        /// </summary>
        public static string en_GB {
            get {
                return ResourceManager.GetString("en-GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (IE).
        /// </summary>
        public static string en_IE {
            get {
                return ResourceManager.GetString("en-IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (NZ).
        /// </summary>
        public static string en_NZ {
            get {
                return ResourceManager.GetString("en-NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (US).
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string eo_EO {
            get {
                return ResourceManager.GetString("eo-EO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (ES).
        /// </summary>
        public static string es_ES {
            get {
                return ResourceManager.GetString("es-ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (MX).
        /// </summary>
        public static string es_MX {
            get {
                return ResourceManager.GetString("es-MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian (EE).
        /// </summary>
        public static string et_EE {
            get {
                return ResourceManager.GetString("et-EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basque (ES).
        /// </summary>
        public static string eu_ES {
            get {
                return ResourceManager.GetString("eu-ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi (IR).
        /// </summary>
        public static string fa_IR {
            get {
                return ResourceManager.GetString("fa-IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish (FI).
        /// </summary>
        public static string fi_FI {
            get {
                return ResourceManager.GetString("fi-FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French (CA).
        /// </summary>
        public static string fr_CA {
            get {
                return ResourceManager.GetString("fr-CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French (FR).
        /// </summary>
        public static string fr_FR {
            get {
                return ResourceManager.GetString("fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galician (ES).
        /// </summary>
        public static string gl_ES {
            get {
                return ResourceManager.GetString("gl-ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (IL).
        /// </summary>
        public static string he_IL {
            get {
                return ResourceManager.GetString("he-IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi (IN).
        /// </summary>
        public static string hi_IN {
            get {
                return ResourceManager.GetString("hi-IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian (HU).
        /// </summary>
        public static string hu_HU {
            get {
                return ResourceManager.GetString("hu-HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian (ID).
        /// </summary>
        public static string id_ID {
            get {
                return ResourceManager.GetString("id-ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian (IT).
        /// </summary>
        public static string it_IT {
            get {
                return ResourceManager.GetString("it-IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JP).
        /// </summary>
        public static string ja_JP {
            get {
                return ResourceManager.GetString("ja-JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian (GE).
        /// </summary>
        public static string ka_GE {
            get {
                return ResourceManager.GetString("ka-GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakh (KZ).
        /// </summary>
        public static string kk_KZ {
            get {
                return ResourceManager.GetString("kk-KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kannada (IN).
        /// </summary>
        public static string kn_IN {
            get {
                return ResourceManager.GetString("kn-IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean (KR).
        /// </summary>
        public static string ko_KR {
            get {
                return ResourceManager.GetString("ko-KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian (LT).
        /// </summary>
        public static string lt_LT {
            get {
                return ResourceManager.GetString("lt-LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian (LV).
        /// </summary>
        public static string lv_LV {
            get {
                return ResourceManager.GetString("lv-LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ml_IN {
            get {
                return ResourceManager.GetString("ml-IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malay (MY).
        /// </summary>
        public static string ms_MY {
            get {
                return ResourceManager.GetString("ms-MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ms_SG {
            get {
                return ResourceManager.GetString("ms-SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian (NO).
        /// </summary>
        public static string nb_NO {
            get {
                return ResourceManager.GetString("nb-NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch (NL).
        /// </summary>
        public static string nl_NL {
            get {
                return ResourceManager.GetString("nl-NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string no_NO {
            get {
                return ResourceManager.GetString("no-NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish (PL).
        /// </summary>
        public static string pl_PL {
            get {
                return ResourceManager.GetString("pl-PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (BR).
        /// </summary>
        public static string pt_BR {
            get {
                return ResourceManager.GetString("pt-BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (PO).
        /// </summary>
        public static string pt_PT {
            get {
                return ResourceManager.GetString("pt-PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian (RO).
        /// </summary>
        public static string ro_RO {
            get {
                return ResourceManager.GetString("ro-RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian (RU).
        /// </summary>
        public static string ru_RU {
            get {
                return ResourceManager.GetString("ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string si_LK {
            get {
                return ResourceManager.GetString("si-LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak (SK).
        /// </summary>
        public static string sk_SK {
            get {
                return ResourceManager.GetString("sk-SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian (SI).
        /// </summary>
        public static string sl_SI {
            get {
                return ResourceManager.GetString("sl-SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian (AL).
        /// </summary>
        public static string sq_AL {
            get {
                return ResourceManager.GetString("sq-AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sr_RS {
            get {
                return ResourceManager.GetString("sr-RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish (SE).
        /// </summary>
        public static string sv_SE {
            get {
                return ResourceManager.GetString("sv-SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil (IN).
        /// </summary>
        public static string ta_IN {
            get {
                return ResourceManager.GetString("ta-IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telugu (IN).
        /// </summary>
        public static string te_IN {
            get {
                return ResourceManager.GetString("te-IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai (TH).
        /// </summary>
        public static string th_TH {
            get {
                return ResourceManager.GetString("th-TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagalog (PH).
        /// </summary>
        public static string tl_PH {
            get {
                return ResourceManager.GetString("tl-PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (TR).
        /// </summary>
        public static string tr_TR {
            get {
                return ResourceManager.GetString("tr-TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian (UA).
        /// </summary>
        public static string uk_UA {
            get {
                return ResourceManager.GetString("uk-UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese (VN).
        /// </summary>
        public static string vi_VN {
            get {
                return ResourceManager.GetString("vi-VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (CH).
        /// </summary>
        public static string zh_CN {
            get {
                return ResourceManager.GetString("zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (HK).
        /// </summary>
        public static string zh_HK {
            get {
                return ResourceManager.GetString("zh-HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (TW).
        /// </summary>
        public static string zh_TW {
            get {
                return ResourceManager.GetString("zh-TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zulu (ZA).
        /// </summary>
        public static string zu_ZA {
            get {
                return ResourceManager.GetString("zu-ZA", resourceCulture);
            }
        }
    }
}
