//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.Shared.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TvGenre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TvGenre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.Shared.Resources.Enum.TvGenre", typeof(TvGenre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action &amp; Adventure.
        /// </summary>
        public static string ActionAdventure {
            get {
                return ResourceManager.GetString("ActionAdventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string Comedy {
            get {
                return ResourceManager.GetString("Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime.
        /// </summary>
        public static string Crime {
            get {
                return ResourceManager.GetString("Crime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentary.
        /// </summary>
        public static string Documentary {
            get {
                return ResourceManager.GetString("Documentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        public static string Drama {
            get {
                return ResourceManager.GetString("Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery.
        /// </summary>
        public static string Mystery {
            get {
                return ResourceManager.GetString("Mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reality.
        /// </summary>
        public static string Reality {
            get {
                return ResourceManager.GetString("Reality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sci-Fi &amp; Fantasy.
        /// </summary>
        public static string SciFiFantasy {
            get {
                return ResourceManager.GetString("SciFiFantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soap.
        /// </summary>
        public static string Soap {
            get {
                return ResourceManager.GetString("Soap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk Show.
        /// </summary>
        public static string Talk {
            get {
                return ResourceManager.GetString("Talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War &amp; Politics.
        /// </summary>
        public static string WarPolitics {
            get {
                return ResourceManager.GetString("WarPolitics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western.
        /// </summary>
        public static string Western {
            get {
                return ResourceManager.GetString("Western", resourceCulture);
            }
        }
    }
}
