//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.WEB.Modules.Auth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SD.WEB.Modules.Auth.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication in progress....
        /// </summary>
        public static string AuthenticationInProgress {
            get {
                return ResourceManager.GetString("AuthenticationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with {0}.
        /// </summary>
        public static string ContinueWith {
            get {
                return ResourceManager.GetString("ContinueWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code you received by email..
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft emails (Outlook, Hotmail, etc.) may not work..
        /// </summary>
        public static string MicrosoftEmails {
            get {
                return ResourceManager.GetString("MicrosoftEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string NothingThisAddress {
            get {
                return ResourceManager.GetString("NothingThisAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Code.
        /// </summary>
        public static string OTPCode {
            get {
                return ResourceManager.GetString("OTPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In or Sign Up.
        /// </summary>
        public static string SignInSignUp {
            get {
                return ResourceManager.GetString("SignInSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the {0} and {1}.
        /// </summary>
        public static string Terms1 {
            get {
                return ResourceManager.GetString("Terms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand that this platform is not for watching and/or downloading movies and TV shows..
        /// </summary>
        public static string Terms2 {
            get {
                return ResourceManager.GetString("Terms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthenticated User.
        /// </summary>
        public static string UnauthenticatedUser {
            get {
                return ResourceManager.GetString("UnauthenticatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to access this page..
        /// </summary>
        public static string YouMustLogged {
            get {
                return ResourceManager.GetString("YouMustLogged", resourceCulture);
            }
        }
    }
}
